### ISSUE TITLE
`IntSetSerializer` is not compatible with RoboVM

### ISSUE THREAD

**Issue by fgnm** [tommyettinger/kryo-more#1]
Hi!
Just spot that the `IntSetSerializer` isn't compatible with RoboVM (latest of both libraries). `PrimitiveIterator` is an API added to Java 8, but RoboVM has limited support to Java 8 API, can this be fixed here or RoboVM must support it?

```
Caused by: java.lang.NoClassDefFoundError: java.util.PrimitiveIterator$OfInt
	at java.lang.VMClassLoader.findClassInClasspathForLoader(Native Method)
	at java.lang.PathClassLoader.findClass(PathClassLoader.java:193)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:515)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:475)
	at com.github.tommyettinger.kryo.jdkgdxds.IntSetSerializer.write(IntSetSerializer.java:39)
	at com.github.tommyettinger.kryo.jdkgdxds.IntSetSerializer.write(IntSetSerializer.java:29)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:85)
	... 12 more
```

**Comment by tommyettinger** [comment]
Hey, Java 7? Are you alive still? [I guess not.](https://endoflife.date/java)

You can use a version of RoboVM that is compatible with Java 8, such as https://www.patreon.com/posts/release-2-3-19-80275446 , or you can use MOE, which claims to support more recent Java. I can't test any of these because I don't own a Mac.

Since jdkgdxds development started in 2020, I've been thinking that dkimitsa would be close to merging Java 8 support, and I've been hoping that for about 3 years now. RoboVM is the only platform that is so out-of-date, backwards, rust-encrusted, antiquated, dilapidated, deprecated, etc... Even GWT and Android support Java 11 now, or at least most of it.

The reason I use `PrimitiveIterator`, and not some custom-defined equivalent, is to avoid the API forking off into a version compatible with jdkgdxds, but not compatible with the standard JDK. The same is true for why I use `Map`, `List`, and `Set`. If RoboVM compatibility will worsen my library, I won't support RoboVM. When RoboVM is using a **living** API version of Java, such as 8, then I can support it. Until then, you can use MOE, or the robovmx branch linked above.

**Comment by fgnm** [comment]
To fix this and probably other similar issues just copy required classes (in appropriate packages) from any JDK 8 source code into `core` project. In that case 5 classes are needed:
- java.util.PrimitiveIterator
- java.util.function.Consumer
- java.util.function.DoubleConsumer
- java.util.function.IntConsumer
- java.util.function.LongConsumer

RoboVM will understand and everything should work fine!

**Comment by tommyettinger** [comment]
Woo, thanks @fgnm ! I think these ~~classes~~ interfaces can be obtained from one of the Android libs or from OpenJDK, but I'm wondering if there might be a way to avoid them entirely. The functional interfaces have the nice property that any lambda  can be assigned to any functional interface type as long as the type signature is compatible, so I could probably redefine the Consumer types just fine. PrimitiveIterator is trickier, but it seems to be barely used in the JDK, which surprises me a little -- only [Spliterator-related code](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/class-use/PrimitiveIterator.OfDouble.html) actually uses any of the PrimitiveIterator types. Spliterator is absolutely not supported by GWT, so it doesn't make sense to write Spliterator code here. The FloatIterator interface in jdkgdxds extends PrimitiveIterator, but isn't one of the nested interfaces defined in PrimitiveIterator, like PrimitiveIterator.OfLong or PrimitiveIterator.OfDouble, so as long as I have some substitute for PrimitiveIterator (and Iterator could work just fine here), there's precedent for an external iterator interface.
